version: "3"
services:
    www:
        build: .
        restart: always
        ports: 
            - "8000:80"
            - "4430:443"
        volumes:
            - .:/var/www/
        networks:
            - default
        stdin_open: true
    db:
        image: mysql
        ports: 
            - "3306:3306"
            - "33060:33060"
        restart: always
        environment:
            MYSQL_DATABASE: myapp
            MYSQL_USER: Q_werty
            MYSQL_PASSWORD: Qwasz#112233
            MYSQL_ROOT_PASSWORD: Qwasz#332211
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - "9090:80"
        restart: always
        environment:
            MYSQL_USER: Q_werty
            MYSQL_PASSWORD: Qwasz#112233
            MYSQL_ROOT_PASSWORD: Qwasz#332211
volumes:
    persistent:
